# Generated by Django 5.0.2 on 2024-02-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='data_id',
            new_name='weather_data_id',
        ),
    ]
