# Generated by Django 5.0.2 on 2024-05-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_rename_state_weatherdata_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
